
services:
  api: 
    image: mefira/schoolhub
    depends_on:
      - postgress
    ports:
      - 1000:1000
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}


    # command: ["uvicorn", "app.main:app","--host","0.0.0.0","--port","1000","--reload"]
  postgress:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgress-db:/var/lib/postgresql/data
volumes:
  postgress-db:
      
