"""empty message

Revision ID: 1e7a7378d541
Revises: 9e7398449031
Create Date: 2025-05-05 17:17:20.689820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7a7378d541'
down_revision: Union[str, None] = '9e7398449031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('current_accedemic_year', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.add_column('student', sa.Column('current_accedemic_semister', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.add_column('student', sa.Column('status', sa.String(), server_default='Active', nullable=True))
    op.drop_column('student', 'class_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('class_year', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_column('student', 'status')
    op.drop_column('student', 'current_accedemic_semister')
    op.drop_column('student', 'current_accedemic_year')
    # ### end Alembic commands ###
