"""empty message

Revision ID: 33c3fb37f680
Revises: b8db1f64df59
Create Date: 2025-05-02 22:01:19.759447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c3fb37f680'
down_revision: Union[str, None] = 'b8db1f64df59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'student', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'email')
    # ### end Alembic commands ###
