"""empty message

Revision ID: 9e7398449031
Revises: 43bb78c7c1e4
Create Date: 2025-05-05 15:27:40.913167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7398449031'
down_revision: Union[str, None] = '43bb78c7c1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('score', sa.Double(), server_default=sa.text('0'), nullable=True))
    op.add_column('assessment', sa.Column('max_score', sa.Double(), server_default=sa.text('0'), nullable=True))
    op.add_column('assessment', sa.Column('semester', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.add_column('assessment', sa.Column('student_accedemic_year', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.drop_column('assessment', 'point')
    op.add_column('enrollment', sa.Column('grade', sa.Double(), server_default=sa.text('0'), nullable=True))
    op.add_column('enrollment', sa.Column('status', sa.String(), server_default='Taking', nullable=True))
    op.add_column('enrollment', sa.Column('total_score', sa.Double(), server_default=sa.text('0'), nullable=True))
    op.add_column('enrollment', sa.Column('total_max_score', sa.Double(), server_default=sa.text('100'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment', 'total_max_score')
    op.drop_column('enrollment', 'total_score')
    op.drop_column('enrollment', 'status')
    op.drop_column('enrollment', 'grade')
    op.add_column('assessment', sa.Column('point', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('assessment', 'student_accedemic_year')
    op.drop_column('assessment', 'semester')
    op.drop_column('assessment', 'max_score')
    op.drop_column('assessment', 'score')
    # ### end Alembic commands ###
