"""empty message

Revision ID: cb51fd30031f
Revises: 1e7a7378d541
Create Date: 2025-05-05 18:36:13.823648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb51fd30031f'
down_revision: Union[str, None] = '1e7a7378d541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('profile_url', sa.String(), server_default='', nullable=True))
    op.add_column('section', sa.Column('representative', sa.String(), nullable=True))
    op.create_foreign_key(None, 'section', 'student', ['representative'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.drop_column('section', 'representative')
    op.drop_column('chat', 'profile_url')
    # ### end Alembic commands ###
